from pathlib import Path


sheets_path = Path("bot/sheets.py")
text = sheets_path.read_text(encoding="utf-8")
old = '''def _format_sheet_intro(service, spreadsheet_id: str, sheet_name: str) -> None:\n    properties = _sheet_properties(service, spreadsheet_id).get(sheet_name)\n    if not properties:\n        return\n    sheet_id = int(properties["sheetId"])\n    requests = [\n        {\n            "repeatCell": {\n                "range": {"sheetId": sheet_id, "startRowIndex": 0, "endRowIndex": 3},\n                "cell": {\n                    "userEnteredFormat": {\n                        "backgroundColor": {"red": 0.94, "green": 0.94, "blue": 0.94},\n                        "wrapStrategy": "WRAP",\n                        "verticalAlignment": "MIDDLE",\n                    }\n                },\n                "fields": "userEnteredFormat(backgroundColor,wrapStrategy,verticalAlignment)",\n            }\n        },\n        {\n            "repeatCell": {\n                "range": {"sheetId": sheet_id, "startRowIndex": 0, "endRowIndex": 1},\n                "cell": {"userEnteredFormat": {"textFormat": {"bold": True}}},\n                "fields": "userEnteredFormat.textFormat.bold",\n            }\n        },\n        {\n            "repeatCell": {\n                "range": {"sheetId": sheet_id, "startRowIndex": 3, "endRowIndex": 4},\n                "cell": {\n                    "userEnteredFormat": {\n                        "backgroundColor": {"red": 0.86, "green": 0.89, "blue": 0.93},\n                        "textFormat": {"bold": True},\n                        "wrapStrategy": "WRAP",\n                    }\n                },\n                "fields": "userEnteredFormat(backgroundColor,textFormat.bold,wrapStrategy)",\n            }\n        },\n        {\n            "updateSheetProperties": {\n                "properties": {\n                    "sheetId": sheet_id,\n                    "gridProperties": {"frozenRowCount": sheet_layout.HEADER_ROW},\n                },\n                "fields": "gridProperties.frozenRowCount",\n            }\n        },\n    ]\n    service.spreadsheets().batchUpdate(\n        spreadsheetId=spreadsheet_id,\n        body={"requests": requests},\n    ).execute()\n'''
new = '''def _format_sheet_intro(service, spreadsheet_id: str, sheet_name: str) -> None:\n    properties = _sheet_properties(service, spreadsheet_id).get(sheet_name)\n    if not properties:\n        return\n    sheet_id = int(properties["sheetId"])\n    requests = [\n        {\n            "repeatCell": {\n                "range": {\n                    "sheetId": sheet_id,\n                    "startRowIndex": 0,\n                    "endRowIndex": sheet_layout.INFO_ROWS,\n                },\n                "cell": {\n                    "userEnteredFormat": {\n                        "backgroundColor": {"red": 0.94, "green": 0.94, "blue": 0.94},\n                        "textFormat": {"bold": True},\n                        "wrapStrategy": "WRAP",\n                        "verticalAlignment": "MIDDLE",\n                    }\n                },\n                "fields": "userEnteredFormat(backgroundColor,textFormat.bold,wrapStrategy,verticalAlignment)",\n            }\n        },\n        {\n            "repeatCell": {\n                "range": {\n                    "sheetId": sheet_id,\n                    "startRowIndex": sheet_layout.HEADER_ROW - 1,\n                    "endRowIndex": sheet_layout.HEADER_ROW,\n                },\n                "cell": {\n                    "userEnteredFormat": {\n                        "backgroundColor": {"red": 0.86, "green": 0.89, "blue": 0.93},\n                        "textFormat": {"bold": True},\n                        "wrapStrategy": "WRAP",\n                    }\n                },\n                "fields": "userEnteredFormat(backgroundColor,textFormat.bold,wrapStrategy)",\n            }\n        },\n        {\n            "updateSheetProperties": {\n                "properties": {\n                    "sheetId": sheet_id,\n                    "gridProperties": {"frozenRowCount": sheet_layout.HEADER_ROW},\n                },\n                "fields": "gridProperties.frozenRowCount",\n            }\n        },\n    ]\n    service.spreadsheets().batchUpdate(\n        spreadsheetId=spreadsheet_id,\n        body={"requests": requests},\n    ).execute()\n'''
if old not in text:
    raise SystemExit("_format_sheet_intro block not found")
sheets_path.write_text(text.replace(old, new, 1), encoding="utf-8")


oidc_path = Path("bot/github_oidc.py")
oidc = oidc_path.read_text(encoding="utf-8")
normal = 'GITHUB_EVENTS = {"schedule", "workflow_dispatch"}'
temporary = '# Temporary one-time allowance for sheet layout v1.0.21.\nGITHUB_EVENTS = {"schedule", "workflow_dispatch", "push"}'
if temporary not in oidc:
    if normal not in oidc:
        raise SystemExit("GITHUB_EVENTS pattern not found")
    oidc = oidc.replace(normal, temporary, 1)
    oidc_path.write_text(oidc, encoding="utf-8")

print("Prepared sheet layout v1.0.21 production patch")
